### PR TITLE
Minimalanalytics (#4)

### PR DESCRIPTION
**Pull request by redwerkz**

### CODE REVIEW

**Comment by Destiner** [comment]
@redwerkz hey, thanks for all your contributions! I don't think we support it yet? Or I at least I don't see it here: https://github.com/Destiner/astro-analytics/tree/main/src

**Comment by redwerkz** [comment]
> @redwerkz hey, thanks for all your contributions! I don't think we support it yet? Or I at least I don't see it here: https://github.com/Destiner/astro-analytics/tree/main/src

not yet, it's a todo -> see empty checkbox [ ]

**Comment by Destiner** [comment]
I see. Will merge that, but in the future let’s keep this list for the platforms we actually support, otherwise it might be confusing.

**Comment by redwerkz** [comment]
> I see. Will merge that, but in the future let’s keep this list for the platforms we actually support, otherwise it might be confusing.

I tried to add the support, but I couldn't figure out how to make it work.

**Pull request merged**
